name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Build and test
      run: ./gradlew clean check
